version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
      image: confluentinc/cp-kafka:latest
      networks:
        - broker-kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      networks:
        - broker-kafka
      depends_on:
        - kafka
      ports:
        - "9000:9000"
      environment:
        KAFKA_BROKERCONNECT: kafka:29092

  postgres:
    image: 'postgres:14'
    container_name: 'conveyor-postgres'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=postgres'
    networks:
      - broker-kafka

  conveyor:
    build: ./conveyor/
    container_name: 'conveyor-app'
    ports:
        - "8081:8081"
    networks:
      - broker-kafka

  application:
    build: ./application/
    container_name: 'application-app'
    ports:
        - "8082:8082"
    networks:
      - broker-kafka

  deal:
    build: ./deal/
    container_name: 'deal-app'
    ports:
        - "8079:8079"
    depends_on:
      - postgres
    environment:
      - 'KAFKA_HOST=kafka'
      - 'KAFKA_PORT=29092'
      - 'DB_SERVER=postgres'
    links:
      - postgres
    networks:
      - broker-kafka

  dossier:
    build: ./dossier/
    container_name: 'dossier-app'
    ports:
        - "8083:8083"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092

    networks:
      - broker-kafka

  gateway:
    build: ./gateway/
    container_name: 'gateway-app'
    ports:
        - "8080:8080"
    networks:
      - broker-kafka
networks:
  broker-kafka:
    driver: bridge


